### ISSUE TITLE
Github's D grammar file is partially broken

### ISSUE THREAD

**Issue by wilzbach** [textmate/d.tmbundle#11]
I was told that Github uses Linguist which in turns uses this D Grammar file?

At least on Github on some pages the D syntax highlighting is broken and I read this is most likely due to an error in the specific language's grammar.
Here are two examples of failed syntax highlighting:

https://gist.github.com/wilzbach/ddc216a90c7a86964c637d676f17a32c
https://github.com/libmir/mir/blob/tinflex/examples/plot_generic.d

**Comment by jacob-carlborg** [comment]
> I was told that Github uses Linguist which in turns uses this D Grammar file?

That's correct.

> At least on Github on some pages the D syntax highlighting is broken and I read this is most likely due to an error in the specific language's grammar.
Here are two examples of failed syntax highlighting:
https://gist.github.com/wilzbach/ddc216a90c7a86964c637d676f17a32c

This one looks like it's identified as a makefile. If you look at the HTML source code there's this `div`:

```html
<div itemprop="text" class="blob-wrapper data type-makefile">
```

It has the class `type-makefile`. For D files it's `type-d`. I'm pretty sure that this bundle is not used to identify the D language.

> https://github.com/libmir/mir/blob/tinflex/examples/plot_generic.d

This file does not exist.

**Comment by sgf** [comment]
hello,how to build project ?

**Comment by jacob-carlborg** [comment]
> hello,how to build a dlang project by this VSCode on windows ?

Not sure I'm following. This is the D bundle for TextMate on macOS. If you're using the same bundle for VSCode, I'm pretty sure it only supports syntax highlighting.

**Comment by Geod24** [comment]
Is this still an issue ?

**Comment by jacob-carlborg** [comment]
No.
