### ISSUE TITLE
Sometimes obligatory new line for full syntax highlighting

### ISSUE THREAD

**Issue by LaurentTreguier** [textmate/d.tmbundle#12]
For some syntax highlighting such as function name or class name, the regex [starts with `^\s*`](https://github.com/textmate/d.tmbundle/blob/master/Syntaxes/D.tmLanguage#L475), which makes it obligatory to have a newline in order to have correct highlighting. Something like this won't be entirely highlighted :
```d
auto highlighted() { return 0; } auto notHighlighted() { return 0; }
```
Though it's ugly, there is technically nothing wrong with this way of writing things.
Is it necessary to start with  `^\s*` for all of the seven places where it's used throughout the file ?

**Comment by jacob-carlborg** [comment]
The reason why it uses `^\s*` because the D grammar is quite complex and the grammar system in TextMate is very limited. If `^\s*` is removed I'm afraid that other lines that are not function declarations will be highlighted as such.

**Comment by infininight** [comment]
Since the issue is making sure it is the start of a new context wouldn't a look-behind of `^|\}|;` correct the issue? (Didn't look very close at the D language to see if that makes sense.)

**Comment by jacob-carlborg** [comment]
@infininight not sure how you mean. I tried replacing `^\s*` with `^|\}|;` and that broke the grammar for function declarations completely.

**Comment by infininight** [comment]
@jacob-carlborg You would have to maintain it being a zero-width assertion, so `(?<=^|\}|;)\s*`.

Was really thinking out loud here, I didn't review the grammar in detail or test this, just tried to look at the purpose for the line requirement.

**Comment by jacob-carlborg** [comment]
@infininight thanks, that worked.
