### ISSUE TITLE
operator => is not displayed correctly on GH

### ISSUE THREAD

**Issue by BBasile** [textmate/d.tmbundle#13]
```D
enum a = b => b.test();
```

**Comment by jacob-carlborg** [comment]
How is it expected to show? Both `=` and `>` highlighted?

**Comment by BBasile** [comment]
Yes. I don't know how the lexer works for text mate but normally you'd accumulate operators chars up to 4 chars or up to a symbol/blank/identifier char and then you lookup for valid combinations of N chars operators, N-1 chars op, N-2 op until the N chars are consumed.

e.g  4 chars can be
- a 4 chars op
- a 3 chars op then a 1 char op
- a 2 chars op then a 2 chars op
- a 2 chars op then two 1 char op
- etc...
