### ISSUE TITLE
highlighting broken for comments

### ISSUE THREAD

**Issue by CodeMyst** [textmate/d.tmbundle#22]
looks like the D highlighting is broken with the ++ comments:

https://github.com/CodeMyst/pastemyst/blob/main/source/pastemyst/paste/create.d#L172-L203

**Comment by jacob-carlborg** [comment]
This looks like a duplicate of https://github.com/textmate/d.tmbundle/issues/20, which has already been fixed. It's up to GitHub incorporate the latest changes of this bundle into their syntax highlighter.

**Comment by CodeMyst** [comment]
ah i see, thank you!
