### ISSUE TITLE
Error when highlighting `to` inside of a string passed to a function call

### ISSUE THREAD

**Issue by stefan-brus-sociomantic** [textmate/d.tmbundle#6]
Reference: https://github.com/stefan-brus-sociomantic/public-sandbox/blob/master/syntax.d

It seems like `to` is treated as a keyword for some reason (it's just a library function, albeit a frequently used one), and this sometimes screws up the highlighting of multi-line strings. The simplest case I have been able to replicate is the one linked above, where to followed by parentheses is present in the 2nd argument of a function call.

**Comment by jacob-carlborg** [comment]
It's a known problem, I'll see if I can come up with a fix. In this case I think "to" is highlighted as a function declaration.

**Comment by jacob-carlborg** [comment]
BTW, "to" should/could be highlighted similar as "string". TextMate also highlights symbols part of the standard library. Although not in the same color as a keyword.
