### ISSUE TITLE
bug with string parsing

### ISSUE THREAD

**Issue by yannick** [textmate/d.tmbundle#7]
sometimes when there are parenthesis within a string all highlighting for the rest of the file gets smashed.
it seems to happen only after a space was within the string and one opening parenthesis is enough.
see screenshot

<img width="415" alt="screen shot 2015-08-02 at 11 40 05 am" src="https://cloud.githubusercontent.com/assets/2794/9025614/03c3290c-390c-11e5-842f-0c4d75290680.png">

**Comment by jacob-carlborg** [comment]
I'm suspecting this is the same issue as #6, which has been fixed. The updates have not yet been pushed to TextMate users. Could you please try to installing the bundle manually from source. Just clone the repository in `~/Library/Application Support/TextMate/Bundles`. It should either be in `TextMate` or `Avian`.

@infininight could you please push the latest changes to the users?

**Comment by yannick** [comment]
@jacob-carlborg i forgot to mention that i was actually on master

**Comment by jacob-carlborg** [comment]
Could you please paste a piece of code as text that shows the issues.

**Comment by yannick** [comment]
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/http/server.d#L1709 
funny, github seems to have the same issue

**Comment by jacob-carlborg** [comment]
> funny, github seems to have the same issue

Github uses this bundle to do the syntax highlighting.

**Comment by infininight** [comment]
@jacob-carlborg Pushed the latest.
