### ISSUE TITLE
dcd support

### ISSUE THREAD

**Issue by yannick** [textmate/d.tmbundle#8]
is it possible to use dcd?

**Comment by jacob-carlborg** [comment]
It's not supported right now but I would like to add support for DCD at some point.

**Comment by jacob-carlborg** [comment]
I've added support for a DCD completion command https://github.com/textmate/d.tmbundle/commit/acc839bf4a00573a81a0e99dbb969aae6559a147. The update is not available through TextMate yet but I've notified the one responsible for updating bundles.

**Comment by infininight** [comment]
And deployed, the bundle will auto update within a few hours.

**Comment by jacob-carlborg** [comment]
I've added support for go-to-definition and documentation for word. I consider this issue fixed now. If there's something else that should be supported, please file a new issue specific for that feature.

**Comment by jacob-carlborg** [comment]
@infininight could you please deploy the D bundle.

**Comment by infininight** [comment]
Deployed.

**Comment by jacob-carlborg** [comment]
Thanks.
